### ISSUE TITLE
Complete Parsing Example?

### ISSUE THREAD

**Issue by fdncred** [JaCraig/SQLParser#1]
Nice start! Is there any examples that demonstrate how to parse a complete sql statement? I reviewed the tests and they look good but they only scratch the surface for parsing.

**Comment by JaCraig** [comment]
Not really. I actually built this more for another library where I needed the ability to tell if a query was read or write. More or less the TSqlParserBaseListener base class walks the resulting parse tree that ANTLR spits out for TSQL. But my need wasn't to parse out everything so I didn't create a complete example.

**Comment by fdncred** [comment]
Thanks
